apiVersion: v1
kind: Service
metadata:
  name: python-scrape-service
  namespace: scrapez
spec:
  selector:
    app: python_scrape
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Deployment
metadata:
  name: python_scrape
  namespace: scrapez
spec:
  selector:
    matchLabels: 
      app: python_scrape
  replicas: 2
  template:
    metadata:
      labels:
        app: python_scrape
    spec:
      containers:
      - name: python_scrape
        image: jabras/python_scrape:latest
        imagePullPolicy: Never
        ports: 500
        - containerPort: 5000
        volumeMounts:
        - name: my-mount-persistent
          mountPath: /var/lib/csv
      volumes:
      - name: my-mount-persistent
        persistentVolumeClaim:
          claimName: my-mount-claim 


