apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mount-persistent 
  namespace: scrapez
spec: 
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-mount-persistent
  namespace: scrapez
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi


